import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/Landing'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import AboutMe from "../components/AboutMe";
import Skills from "../components/skills/Skills";
import Projects from '../components/projects/Projects'
import { EnvContext } from '../context';
const Home = (props: any) => {

  return (
    <EnvContext.Provider value={{projectId:props.projectId,dataset:props.dataset}}>

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main '>
     <div className="relative w-full bg-[url('../assets/img/bg-hero.jpg')] bg-cover">
       <div className="bg-center bg-cover bg-no-repeat absolute inset-0 z-20 bg-gradient-to-r from-hero-gradient-from to-hero-gradient-to">
    </div>
    <div className='relative z-50'>

     <NavBar/> 
     <Landing/>
    </div>
     </div>
     <div>
        <AboutMe />
        <Skills />
      <Projects projects={props.projects?props.projects:[]}/>
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
</EnvContext.Provider>
  )
}

export default Home

export const getServerSideProps=async()=>{
   const query = encodeURIComponent(`*[_type=="project"]`);
   const projectId = process.env.PROJECT_ID;
  const dataset = process.env.PROJECT_DATASET;
  const url = `https://${projectId}.api.sanity.io/v1/data/query/${dataset}?query=${query}`;
  const resp = await fetch(url).then((res) => res.json());
  console.log("server response:",resp)
  return {
    props:{
      projects:resp.result,
      projectId,
      dataset
    }
  }
  
}
